---
# file: roles/cdh_hadoop_namenode/tasks/main.yml

- name: install hadoop-hdfs-namenode via apt
  apt: pkg=hadoop-hdfs-namenode={{ cdh_hadoop_version }}
  tags: hadoop

- name: configure rsyslog for hadoop-hdfs-namenode
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hadoop-hdfs-namenode.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog
