- hosts: oozie_metastore
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  roles:
    - postgresql_server

- hosts: hive_metastore:hue_server:datanodes
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  roles:
    - cdh_hive_config
  tags: argh

- hosts: hive_metastore
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  roles:
    - postgresql_jdbc_for_hive

- hosts: hive_metastore
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  sudo_user: postgres
  tasks:
    - postgresql_db: name=metastore
      tags:
        - postgres
        - hive
    - postgresql_user: db=metastore name=hiveuser password=hive_{{ site_name }} priv=CONNECT
      tags:
        - postgres
        - hive
    - shell: psql --dbname=metastore --file=/usr/lib/hive/scripts/metastore/upgrade/postgres/hive-schema-0.10.0.postgres.sql
      tags:
        - postgres
        - hive
    - shell: psql --dbname=metastore --command="GRANT ALL ON ALL TABLES IN SCHEMA public TO hiveuser;"
      tags:
        - postgres
        - hive

- hosts: hive_metastore
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  roles:
    - cdh_hive_metastore

- hosts: namenodes[0]
  accelerate: "{{ accelerate }}"
  user: ansibler
  sudo: true
  sudo_user: hdfs
  tasks:
    - name: create a /user/hive/warehouse directory on the cluster
      shell: creates=/data/dfs/.hivewarehousedircreated hadoop fs -mkdir /user/hive/warehouse && touch /data/dfs/.hivewarehousedircreated
      tags:
        - hive
    - name: make sure the /user/hive/warehouse directory has the correct permissions
      shell: creates=/data/dfs/.hivewarehousedirchmodded sleep 5 && hadoop fs -chmod -R 1777 /user/hive/warehouse && touch /data/dfs/.hivewarehousedirchmodded
      tags:
        - hive
    - name: make sure the /user/hive directory has the correct owner
      shell: creates=/data/dfs/.hivedirchowned sleep 5 && hadoop fs -chown -R hive:hive /user/hive && touch /data/dfs/.hivedirchowned
      tags:
        - hadoop