---
# Site Configuration
# ==================
# All services

- include: prerequisists.yml

- include: notify_email.yml

- include: monitoring.yml

- include: hadoop.yml

- include: hbase.yml

- include: hive.yml

- include: oozie.yml

- include: sqoop.yml

- include: sqoop2.yml

- include: hue.yml

- include: presto.yml