- name: no conflicting Java installations present
  apt: pkg={{ item }} state=absent
  with_items:
    - oracle-java7-installer
    - openjdk-6-jre-lib
    - openjdk-6-jre
    - openjdk-6-jdk
  tags: java

- name: openjdk-7-jdk is present
  apt: pkg=openjdk-7-jdk state=present
  tags: java

- name: openjdk set as JAVA_HOME globally
  lineinfile:
    dest=/etc/environment
    regexp=JAVA_HOME=
    line=JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
    state=present
    backrefs=no
  tags: java

- name: set fact jdk_installed
  set_fact: jdk_installed=true
  tags: java