---
- name: install oozie now
  apt: pkg={{ item }}
  with_items:
    - oozie
  notify:
    - restart oozie
    
- name: configure oozie in /etc/oozie/conf.dist/oozie-site.xml
  template: src=oozie-site.xml dest=/etc/oozie/conf.dist/oozie-site.xml owner=root group=root mode=0644
  notify:
    - restart oozie
  tags:
    - oozie
    - configuration
    
- name: configure Oozie to use YARN
  lineinfile:
    dest=/etc/oozie/conf/oozie-env.sh
    regexp=CATALINA_BASE=
    line=export\ CATALINA_BASE=/usr/lib/oozie/oozie-server
    state=present
    backrefs=yes
  notify:
    - restart oozie
  tags: configuration
  
- name: create oozie DB schema
  sudo_user: oozie
  command: /usr/lib/oozie/bin/ooziedb.sh create -run
  notify:
    - restart oozie
  ignore_errors: True
  tags:
    - oozie
    - configuration

# Create Oozie shared libs
- name: make oozie user directory on HDFS
  sudo_user: hdfs
  command: hadoop fs -mkdir  -p /user/oozie
  tags:
    - oozie
    
- name: chown oozie user directory on HDFS
  sudo_user: hdfs
  command: hadoop fs -chown oozie:oozie /user/oozie
  tags:
    - oozie
    
- name: make tmp dir for oozie shared libs
  command: mkdir -p /tmp/ooziesharelib creates=/tmp/ooziesharelib
  tags:
    - oozie
    
- name: decompress oozie shared libs to tmp dir
  command: tar xzf /usr/lib/oozie/oozie-sharelib-yarn.tar.gz chdir=/tmp/ooziesharelib
  tags:
    - oozie

- name: copy oozie shared libs to HDFS
  sudo_user: oozie
  command: hadoop fs -put share /user/oozie/share chdir=/tmp/ooziesharelib
  tags:
    - oozie