---
- name: create oozie user in postgres
  postgresql_user: name=oozie password=oozie encrypted=yes login_password=yes role_attr_flags=NOSUPERUSER,CREATEDB,NOCREATEROLE
  sudo_user: postgres
  notify:
    - restart postgresql
    
- name: create oozie db in postgres
  postgresql_db: name=oozie owner=oozie encoding='UTF-8' lc_collate='en_US.UTF8' lc_ctype='en_US.UTF8' template='template0'
  sudo_user: postgres
  notify:
    - restart postgresql
  
- name: configure postgresql to listen on all network interface
  lineinfile:
    dest=/etc/postgresql/9.1/main/postgresql.conf
    regexp=listen_addresses
    line=listen_addresses\ =\ \'*\'
    state=present
    backrefs=yes
  notify:
    - restart postgresql
  tags:
    - configuration


- name: configure postgresql to allow non-conforming strings
  lineinfile:
    dest=/etc/postgresql/9.1/main/postgresql.conf
    regexp=standard_conforming_strings
    line=standard_conforming_strings\ =\ off
    state=present
    backrefs=yes
  notify:
    - restart postgresql
  tags:
    - configuration


- name: configure postgresql to allow oozie on 0.0.0.0
  lineinfile:
    dest=/etc/postgresql/9.1/main/pg_hba.conf
    regexp="host oozie oozie 0.0.0.0/0 md5"
    line="host oozie oozie 0.0.0.0/0 md5"
    state=present
  notify:
    - restart postgresql
  tags:
    - configuration