---
# file: roles/cdh_hadoop_common/tasks/main.yml

- name: install base Hadoop packages via apt
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - hadoop={{ cdh_hadoop_version }}
    - hadoop-hdfs={{ cdh_hadoop_version }}
    - hadoop-lzo-cdh4=0.4.15-1.gplextras.p0.152~precise-gplextras4.3.0
    - hadoop-yarn={{ cdh_hadoop_version }}
  tags: hadoop

- name: create the /data directory
  file: path=/data owner=hdfs group=hdfs state=directory
  tags: hadoop

- name: create the /data/dfs directory
  file: path=/data/dfs owner=hdfs group=hdfs state=directory
  tags: hadoop
