---
- name: install hue meta-package and hue server
  apt: pkg={{ item }}
  with_items:
    - hue={{ cdh_hue_version }}
    - hue-server={{ cdh_hue_version }}

- name: Use hue.ini file with correct properties
  template: dest=/etc/hue/conf/hue.ini src=hue.ini
  notify:
    - restart hue
  tags: configuration
