---
- name: install hue meta-package and hue server
  apt: pkg={{ item }}
  with_items:
    - hue
    - hue-server

- name: set WebHDFS URL for primary NameNode in hue.ini
  lineinfile:
    dest=/etc/hue/conf/hue.ini
    regexp=webhdfs_url=
    line=webhdfs_url=http://{{ hostvars[groups['namenodes'][0]]['ansible_default_ipv4']['address'] }}:50070/webhdfs/v1/
    state=present
    backrefs=yes
  notify:
    - restart hue
  tags: configuration

- name: set hive_conf_dir in hue.ini
  lineinfile:
    dest=/etc/hue/conf/hue.ini
    regexp=hive_conf_dir=
    line=hive_conf_dir=/etc/hive/conf.{{ site_name }}/
    state=present
    backrefs=yes
  notify:
    - restart hue
  tags: configuration

- name: Ensure Hue submits jobs to YARN cluster
  lineinfile:
    dest=/etc/hue/conf/hue.ini
    regexp=##\ submit_to=False
    line=submit_to=True
    state=present
    backrefs=yes
  notify:
    - restart hue
  tags: configuration

- name: Ensure Hue does not try to submit jobs to a MRv1 cluster
  lineinfile:
    dest=/etc/hue/conf/hue.ini
    regexp=##\ submit_to=True
    line=submit_to=False
    state=present
    backrefs=yes
  notify:
    - restart hue
  tags: configuration

- name: Ensure hue is actually started
  sudo_user: hue
  service: name=hue state=started
